// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaKcHGUH6B0GY9JwssjTxF9gw1LXp2DN8',
    appId: '1:490996388029:web:27eaced65731c1beb127d4',
    messagingSenderId: '490996388029',
    projectId: 'quizzenglishlearn',
    authDomain: 'quizzenglishlearn.firebaseapp.com',
    storageBucket: 'quizzenglishlearn.appspot.com',
    measurementId: 'G-HPD4V5RVME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4mOX2G4gJOVQB8dPBDg_j8ybpULqyZI',
    appId: '1:490996388029:android:def182d2b5c48f25b127d4',
    messagingSenderId: '490996388029',
    projectId: 'quizzenglishlearn',
    storageBucket: 'quizzenglishlearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4UrcPJqyT0-5qmdwCpNxPwx1oo8NC_A',
    appId: '1:490996388029:ios:62b3dd6aa4920e93b127d4',
    messagingSenderId: '490996388029',
    projectId: 'quizzenglishlearn',
    storageBucket: 'quizzenglishlearn.appspot.com',
    iosClientId: '490996388029-3rkk9ns0og2u285ain2n4572po9ri8or.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
